[package]
name = "toro"
version = "0.1.0"
edition = "2021"
authors = ["Tanapol Prucksakorn <tanapol.pr@gmail.com>"]
license = "MIT"
repository = "https://github.com/zynaxsoft/restaurant"
readme = "README.md"

[dependencies]
anyhow = "1.0"
